# Generated by Django 3.1.2 on 2020-10-19 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('task_id', models.CharField(blank=True, default='', max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('timeout', 'Time Out'), ('failed', 'Failed'), ('successful', 'Successful')], default='pending', max_length=20)),
                ('locations', models.JSONField()),
                ('num_vehicles', models.IntegerField(default=1)),
                ('starting_location', models.IntegerField(default=0)),
                ('full_result', models.JSONField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
