version: "3.8"

services:
  # Optimisation Web Service
  web:
    build:
      context: web

    depends_on:
      - db
      - optimisation_service
      - bugsbunny

    environment:
      DJANGO_SETTINGS_MODULE: optimisation_web.settings
      PYTHONPATH: /optimisation_web

    ports:
      - 8005:8005

    networks:
      - db
      - messagequeue

    environment:
      PYTHONPATH: /optimisation_web

    volumes:
      - ./web/:/optimisation_web

    stdin_open: true
    tty: true

  # Optimisation web service - celery worker
  celery:
    build:
      context: web

    networks:
      - db
      - messagequeue

    volumes:
      - ./web/:/optimisation_web

    depends_on:
      - bugsbunny
      - db

    command: celery -A optimisation_web.celery.app worker -l INFO

    stdin_open: true
    tty: true

  # Optimisation web service - database
  db:
    image: postgres

    environment:
      POSTGRES_DB: optimisation
      POSTGRES_USER: optimisation
      POSTGRES_PASSWORD: topsecret

    ports:
      - 5432:5432

    networks:
      - db

  # Optimisation service - celery worker
  optimisation_service:
    build:
      context: optimisation_service

    depends_on:
      - bugsbunny

    environment:
      - PYTHONPATH=/optimisation_service
      - C_FORCE_ROOT=true

    networks:
      - messagequeue

    volumes:
      - ./optimisation_service:/optimisation_service

  # Message queue broker
  bugsbunny:
    image: rabbitmq:3-management

    ports:
      - 5672:5672
      - 15672:15672

    networks:
      - messagequeue

    volumes:
      - bugsbunny_data:/data

  # Message queue broker - monitoring
  flower:
    image: mher/flower

    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@bugsbunny
      - FLOWER_PORT=5555

    ports:
      - 5555:5555

    networks:
      - messagequeue

    depends_on:
      - bugsbunny

networks:
  db:
  messagequeue:


volumes:
  bugsbunny_data:
